### ISSUE TITLE
Train error

### ISSUE THREAD

**Issue by hellojialee** [anatolix/keras_Realtime_Multi-Person_Pose_Estimation#15]
When I run the train code, errors occurred.  Dose this happened because of the version of python and Keras? I have fixed some compatibility errors. I use python 2.7 and keras 2.02. Grateful for help!

Traceback (most recent call last):
  File "/home/jia/Desktop/keras_Realtime_Multi-Person_Pose_Estimation-new-generation/training/train_pose.py", line 32, in <module>
    train(config, model, train_client, val_client, iterations_per_epoch, validation_steps, metrics_id, epoch, use_client_gen, callbacks_list)
  File "/home/jia/Desktop/keras_Realtime_Multi-Person_Pose_Estimation-new-generation/training/train_common.py", line 158, in train
    initial_epoch=epoch
  File "/home/jia/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/jia/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/keras/engine/training.py", line 1725, in fit_generator
    self._make_train_function()
  File "/home/jia/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/keras/engine/training.py", line 937, in _make_train_function
    self.total_loss)
TypeError: get_updates() takes exactly 3 arguments (4 given)

**Comment by anatolix** [comment]
To be honest i've never tested it on python 2.7 and most probably it shouldn't fork since i use print("") not print ""

But this paticular error most probably from keras version I use fresh version from github it is 2.1.3 becuase using several gpu feature available only in new keras
