### ISSUE TITLE
Weird error when training. 

### ISSUE THREAD

**Issue by piperod** [anatolix/keras_Realtime_Multi-Person_Pose_Estimation#4]
I got this error. I think is related with the changes I made for adapting it to fewer annotations. But I don't know exactly where to address it so the shapes match. 

Traceback (most recent call last):
  File "/groups/branson/home/rodriguezi2/miniconda3/envs/pose/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/groups/branson/home/rodriguezi2/miniconda3/envs/pose/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/groups/branson/home/rodriguezi2/miniconda3/envs/pose/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [20,46,46,15] vs. [20,46,46,38]
	 [[Node: loss/weight_stage1_L1_loss/sub = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_weight_stage1_L1_target_0_4/_1115, weight_stage1_L1/mul)]]
	 [[Node: loss/weight_stage3_L1_loss/Mean_2/_1243 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_7917_loss/weight_stage3_L1_loss/Mean_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_pose.py", line 187, in <module>
    initial_epoch=last_epoch
  File "/groups/branson/home/rodriguezi2/miniconda3/envs/pose/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/groups/branson/home/rodriguezi2/miniconda3/envs/pose/lib/python3.6/site-packages/keras/engine/training.py", line 2077, in fit_generator
    class_weight=class_weight)
  File "/groups/branson/home/rodriguezi2/miniconda3/envs/pose/lib/python3.6/site-packages/keras/engine/training.py", line 1797, in train_on_batch
    outputs = self.train_function(ins)
  File "/groups/branson/home/rodriguezi2/miniconda3/envs/pose/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2332, in __call__
    **self.session_kwargs)
  File "/groups/branson/home/rodriguezi2/miniconda3/envs/pose/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/groups/branson/home/rodriguezi2/miniconda3/envs/pose/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/groups/branson/home/rodriguezi2/miniconda3/envs/pose/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/groups/branson/home/rodriguezi2/miniconda3/envs/pose/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [20,46,46,15] vs. [20,46,46,38]
	 [[Node: loss/weight_stage1_L1_loss/sub = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_weight_stage1_L1_target_0_4/_1115, weight_stage1_L1/mul)]]
	 [[Node: loss/weight_stage3_L1_loss/Mean_2/_1243 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_7917_loss/weight_stage3_L1_loss/Mean_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'loss/weight_stage1_L1_loss/sub', defined at:
  File "train_pose.py", line 177, in <module>
    model.compile(loss=eucl_loss, optimizer=multisgd)
  File "/groups/branson/home/rodriguezi2/miniconda3/envs/pose/lib/python3.6/site-packages/keras/engine/training.py", line 860, in compile
    sample_weight, mask)
  File "/groups/branson/home/rodriguezi2/miniconda3/envs/pose/lib/python3.6/site-packages/keras/engine/training.py", line 460, in weighted
    score_array = fn(y_true, y_pred)
  File "train_pose.py", line 115, in eucl_loss
    l = K.sum(K.square(x - y)) / batch_size / 2
  File "/groups/branson/home/rodriguezi2/miniconda3/envs/pose/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 894, in binary_op_wrapper
    return func(x, y, name=name)
  File "/groups/branson/home/rodriguezi2/miniconda3/envs/pose/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 4636, in _sub
    "Sub", x=x, y=y, name=name)
  File "/groups/branson/home/rodriguezi2/miniconda3/envs/pose/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/groups/branson/home/rodriguezi2/miniconda3/envs/pose/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/groups/branson/home/rodriguezi2/miniconda3/envs/pose/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Incompatible shapes: [20,46,46,15] vs. [20,46,46,38]
	 [[Node: loss/weight_stage1_L1_loss/sub = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_weight_stage1_L1_target_0_4/_1115, weight_stage1_L1/mul)]]
	 [[Node: loss/weight_stage3_L1_loss/Mean_2/_1243 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_7917_loss/weight_stage3_L1_loss/Mean_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by anatolix** [comment]
Looks like you changed py_rmpe_config.py and get fewer parts, but hasn't changed model here
https://github.com/anatolix/keras_Realtime_Multi-Person_Pose_Estimation/blob/master/training/ds_generators.py
look for 
```
        self.split_point = 38
        self.vec_num = 38
        self.heat_num = 19
```

Yes in ideal world it will be in one config, but I haven't touched this code yet

**Comment by piperod** [comment]
So vec_num and split_point, 38,  is related with left and right sides. and 19 with the number of annotations?

**Comment by anatolix** [comment]
38 is related to X and Y coordinates of paf, each paf is direction vector (x,y).
